// Local-only adapter. Never bundled in the production Worker.
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import worker from './worker.mjs';
const localRoot=path.resolve('.sites-runtime');fs.mkdirSync(localRoot,{recursive:true});const db=new DatabaseSync(path.join(localRoot,'preview.sqlite'));
db.exec('CREATE TABLE IF NOT EXISTS _local_migrations (name TEXT PRIMARY KEY)');
if(fs.existsSync('drizzle'))for(const name of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort()){if(!db.prepare('SELECT name FROM _local_migrations WHERE name=?').get(name)){db.exec(fs.readFileSync(path.join('drizzle',name),'utf8'));db.prepare('INSERT INTO _local_migrations VALUES (?)').run(name)}}
const DB={prepare(sql){let values=[];return{bind(...p){values=p;return this},async first(){return db.prepare(sql).get(...values)||null},async all(){return{results:db.prepare(sql).all(...values)}},async run(){return db.prepare(sql).run(...values)}}}};
DB.batch=async statements=>{db.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());db.exec('COMMIT');return results}catch(error){db.exec('ROLLBACK');throw error}};
const bucket=path.join(localRoot,'objects');fs.mkdirSync(bucket,{recursive:true});const fileKey=key=>path.join(bucket,Buffer.from(key).toString('hex'));
const BUCKET={async put(key,value){fs.writeFileSync(fileKey(key),Buffer.from(value))},async get(key){return fs.existsSync(fileKey(key))?{body:fs.readFileSync(fileKey(key))}:null},async delete(key){fs.rmSync(fileKey(key),{force:true})}};
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.xml':'application/xml','.txt':'text/plain; charset=utf-8','.csv':'text/csv; charset=utf-8','.svg':'image/svg+xml','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png'};
const ASSETS={async fetch(req){const url=new URL(req.url);let decoded;try{decoded=decodeURIComponent(url.pathname)}catch{return new Response('Bad path',{status:400})}const root=path.resolve('dist/client');let file=path.resolve(root,'.'+decoded);if(file!==root&&!file.startsWith(root+path.sep))return new Response('Forbidden',{status:403});if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)&&!path.extname(file))file=path.join(file,'index.html');let status=200;if(!fs.existsSync(file)){file=path.join(root,'404.html');status=404}return new Response(req.method==='HEAD'?null:fs.readFileSync(file),{status,headers:{'Content-Type':mime[path.extname(file)]||'application/octet-stream'}})}};
const server=http.createServer(async(req,res)=>{try{const origin='http://127.0.0.1:4173';if(!['127.0.0.1:4173','localhost:4173'].includes(req.headers.host)){res.writeHead(403);res.end();return}const url=new URL(req.url,origin);const headers=new Headers();for(const [k,v]of Object.entries(req.headers))if(!k.startsWith('oai-authenticated-user-')&&v!==undefined)headers.set(k,Array.isArray(v)?v.join(','):v);if(['/signin-with-chatgpt','/signout-with-chatgpt'].includes(url.pathname)){const ret=url.searchParams.get('return_to');const safe=ret?.startsWith('/')&&!ret.startsWith('//')&&!ret.includes('\\')?ret:'/';res.writeHead(302,{'Location':safe,'Set-Cookie':`tt_local=${url.pathname.startsWith('/signin')?'1':''}; HttpOnly; SameSite=Lax; Path=/`,'Cache-Control':'no-store'});res.end();return}if((req.headers.cookie||'').split(';').some(v=>v.trim()==='tt_local=1')){headers.set('oai-authenticated-user-id','local-preview-user');headers.set('oai-authenticated-user-email','preview@example.test');headers.set('oai-authenticated-user-full-name','Cliente%20de%20Teste');headers.set('oai-authenticated-user-full-name-encoding','percent-encoded-utf-8')}const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>11*1024*1024){res.writeHead(413);res.end();return}chunks.push(chunk)}const request=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const response=await worker.fetch(request,{DB,BUCKET,ASSETS,ADMIN_USER_IDS:'local-preview-user'},{});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch(err){console.error(err.message);res.writeHead(500);res.end('Local preview error')}});server.listen(4173,'127.0.0.1',()=>console.log('Local: http://127.0.0.1:4173'));

