const MAX_BODY=65536,MAX_FILE=10*1024*1024;
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
export function identity(request){const id=request.headers.get('oai-authenticated-user-id'),email=request.headers.get('oai-authenticated-user-email');if(!id||!email)return null;let name=email;try{if(request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8')name=decodeURIComponent(request.headers.get('oai-authenticated-user-full-name')||email)}catch{}return{id,email,name}}
function query(env,sql,...params){if(!env.DB)throw new HttpError(503,'Banco de dados temporariamente indisponível.');return env.DB.prepare(sql).bind(...params)}
async function all(env,sql,...params){return(await query(env,sql,...params).all()).results||[]}
const text=(data,key,min=1,max=500)=>{const value=typeof data[key]==='string'?data[key].trim():'';if(value.length<min||value.length>max)throw new HttpError(400,'Confira o campo '+key+'.');return value};
const number=(data,key,min=0,max=1e10)=>{if(data[key]===''||data[key]==null)throw new HttpError(400,'Informe '+key+'.');const value=Number(data[key]);if(!Number.isFinite(value)||value<min||value>max)throw new HttpError(400,'Valor inválido no campo '+key+'.');return value};
const date=(data,key)=>{const value=text(data,key,10,10),parsed=new Date(value+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(parsed.getTime())||parsed.toISOString().slice(0,10)!==value)throw new HttpError(400,'Data inválida.');return value};
async function body(request){if(!request.headers.get('Content-Type')?.includes('application/json'))throw new HttpError(415,'Envie os dados em JSON.');const bytes=await limitedBytes(request,MAX_BODY);let value;try{value=JSON.parse(new TextDecoder().decode(bytes))}catch{throw new HttpError(400,'Dados inválidos.')}if(!value||Array.isArray(value)||typeof value!=='object')throw new HttpError(400,'Dados inválidos.');return value}
async function limitedBytes(request,max){if(Number(request.headers.get('Content-Length')||0)>max)throw new HttpError(413,'O arquivo ou formulário excede o limite permitido.');if(!request.body)return new Uint8Array();const reader=request.body.getReader();let length=0,chunks=[];while(true){const {value,done}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();throw new HttpError(413,'O arquivo ou formulário excede o limite permitido.')}chunks.push(value)}const result=new Uint8Array(length);let offset=0;for(const chunk of chunks){result.set(chunk,offset);offset+=chunk.length}return result}
function sameOrigin(request){const origin=request.headers.get('Origin');if((origin&&origin!==new URL(request.url).origin)||request.headers.get('Sec-Fetch-Site')==='cross-site')throw new HttpError(403,'Origem não autorizada.');}
async function insert(env,table,user,values){const id=crypto.randomUUID(),created_at=new Date().toISOString();const row={id,user_id:user.id,...values,created_at};const columns=Object.keys(row);await query(env,`INSERT INTO ${table} (${columns.join(',')}) VALUES (${columns.map(()=>'?').join(',')})`,...Object.values(row)).run();return{id,created_at}}
const ownerTables=['transactions','invoices','documents','employees','obligations','messages','leads'];
async function handleApi(request,env,user,url){if(!user)throw new HttpError(401,'Entre na sua conta para continuar.');const method=request.method,route=url.pathname.slice(4);if(!['GET','HEAD'].includes(method))sameOrigin(request);
 const isAdmin=String(env.ADMIN_USER_IDS||'').split(',').map(s=>s.trim()).filter(Boolean).includes(user.id);
 if(route.startsWith('/admin')){if(!isAdmin)throw new HttpError(403,'Acesso administrativo não autorizado.');if(method==='GET'&&route==='/admin')return json({profiles:await all(env,'SELECT * FROM profiles ORDER BY created_at DESC LIMIT 200'),leads:await all(env,'SELECT * FROM leads ORDER BY created_at DESC LIMIT 200'),messages:await all(env,'SELECT * FROM messages ORDER BY created_at DESC LIMIT 200')});if(method==='PATCH'&&/^\/admin\/leads\/[a-f0-9-]+$/.test(route)){const data=await body(request),status=text(data,'status');if(!['Recebida','Em análise','Em atendimento','Concluída'].includes(status))throw new HttpError(400,'Status inválido.');const id=route.split('/')[3];if(!await query(env,'SELECT id FROM leads WHERE id = ?',id).first())throw new HttpError(404,'Solicitação não encontrada.');await query(env,'UPDATE leads SET status = ? WHERE id = ?',status,id).run();return json({saved:true})}if(method==='POST'&&route==='/admin/messages'){const data=await body(request),target=text(data,'user_id',1,200);const exists=await query(env,'SELECT user_id FROM profiles WHERE user_id = ? UNION SELECT user_id FROM leads WHERE user_id = ? LIMIT 1',target,target).first();if(!exists)throw new HttpError(404,'Cliente não encontrado.');return json(await insert(env,'messages',{id:target},{body:text(data,'body',2,4000),role:'staff'}),201)}throw new HttpError(404,'Recurso administrativo não encontrado.');}
 if(method==='DELETE'&&route==='/account'){const data=await body(request);if(data.confirmation!=='EXCLUIR MEUS DADOS')throw new HttpError(400,'Confirme a exclusão dos dados.');const docs=await all(env,'SELECT object_key FROM documents WHERE user_id = ?',user.id);if(docs.length&&!env.BUCKET)throw new HttpError(503,'Armazenamento indisponível. Tente novamente.');for(const doc of docs)await env.BUCKET.delete(doc.object_key);await env.DB.batch([...ownerTables,'profiles'].map(t=>query(env,`DELETE FROM ${t} WHERE user_id = ?`,user.id)));return json({deleted:true})}
 const recordMatch=route.match(/^\/(transactions|invoices|employees|obligations|documents|messages)\/([a-f0-9-]+)$/);
 if(recordMatch&&['DELETE','PATCH'].includes(method)){const [,table,id]=recordMatch;const record=await query(env,`SELECT * FROM ${table} WHERE id = ? AND user_id = ?`,id,user.id).first();if(!record)throw new HttpError(404,'Registro não encontrado.');if(table==='messages'&&record.role==='staff')throw new HttpError(403,'Mensagens da equipe não podem ser alteradas pelo cliente.');if(method==='DELETE'){if(table==='documents'){if(!env.BUCKET)throw new HttpError(503,'Armazenamento indisponível.');await env.BUCKET.delete(record.object_key)}await query(env,`DELETE FROM ${table} WHERE id = ? AND user_id = ?`,id,user.id).run();return json({deleted:true})}const data=await body(request);let values;if(table==='transactions'){const kind=text(data,'kind');if(!['income','expense'].includes(kind))throw new HttpError(400,'Tipo de movimento inválido.');values={description:text(data,'description',2),kind,amount:number(data,'amount',.01),date:date(data,'date')}}else if(table==='invoices')values={customer:text(data,'customer',2,180),description:text(data,'description',2),amount:number(data,'amount',.01)};else if(table==='employees')values={name:text(data,'name',2,120),role:text(data,'role',2,120),salary:number(data,'salary'),start_date:date(data,'start_date')};else if(table==='obligations'){const status=text(data,'status');if(!['Pendente','Pago','Concluída'].includes(status))throw new HttpError(400,'Status inválido.');values={title:text(data,'title',2,200),amount:number(data,'amount'),due_date:date(data,'due_date'),status}}else throw new HttpError(405,'Este registro não pode ser editado.');await query(env,`UPDATE ${table} SET ${Object.keys(values).map(k=>k+' = ?').join(',')} WHERE id = ? AND user_id = ?`,...Object.values(values),id,user.id).run();return json({saved:true})}
 if(method==='GET'&&route==='/me')return json({user});
 if(method==='GET'&&route==='/dashboard'){const profile=await query(env,'SELECT * FROM profiles WHERE user_id = ?',user.id).first();const results=await Promise.all(ownerTables.map(t=>all(env,`SELECT * FROM ${t} WHERE user_id = ? ORDER BY created_at DESC LIMIT 200`,user.id)));return json({user,profile,isAdmin,...Object.fromEntries(ownerTables.map((t,i)=>[t,results[i]]))})}
 if(method==='PUT'&&route==='/profile'){const data=await body(request),name=text(data,'name',2,120),company=text(data,'company',2,180),city=text(data,'city',2,120);await query(env,'INSERT INTO profiles (user_id,name,email,company,city,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,email=excluded.email,company=excluded.company,city=excluded.city',user.id,name,user.email,company,city,new Date().toISOString()).run();return json({saved:true})}
 if(method==='POST'&&route==='/leads'){const data=await body(request);if(data.consent!==true)throw new HttpError(400,'Confirme a política de privacidade.');const email=text(data,'email',3,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpError(400,'Informe um e-mail válido.');const kind=text(data,'kind',1,20);if(!['opening','contact'].includes(kind))throw new HttpError(400,'Tipo de solicitação inválido.');const recent=await query(env,"SELECT COUNT(*) AS total FROM leads WHERE user_id = ? AND created_at > ?",user.id,new Date(Date.now()-3600000).toISOString()).first();if(recent.total>=20)throw new HttpError(429,'Você já enviou várias solicitações. Tente novamente mais tarde.');const values={kind,name:text(data,'name',2,120),email};if(kind==='opening'){Object.assign(values,{activity:text(data,'activity',2,500),city:text(data,'city',2,120),state:text(data,'state',2,2),revenue:number(data,'revenue'),employees:text(data,'employees',2,100),phone:text(data,'phone',10,30)});if(!'AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ').includes(values.state))throw new HttpError(400,'Estado inválido.');if(values.phone.replace(/\D/g,'').length<10)throw new HttpError(400,'Confira o telefone e o DDD.')}else Object.assign(values,{subject:text(data,'subject',2,200),message:text(data,'message',2,4000)});return json(await insert(env,'leads',user,values),201)}
 if(method==='POST'&&route==='/transactions'){const data=await body(request),kind=text(data,'kind');if(!['income','expense'].includes(kind))throw new HttpError(400,'Tipo de movimento inválido.');return json(await insert(env,'transactions',user,{description:text(data,'description',2),kind,amount:number(data,'amount',.01),date:date(data,'date')}),201)}
 if(method==='POST'&&route==='/invoices'){const data=await body(request);return json(await insert(env,'invoices',user,{customer:text(data,'customer',2,180),description:text(data,'description',2),amount:number(data,'amount',.01),status:'draft'}),201)}
 if(method==='POST'&&route==='/employees'){const data=await body(request);return json(await insert(env,'employees',user,{name:text(data,'name',2,120),role:text(data,'role',2,120),salary:number(data,'salary'),start_date:date(data,'start_date')}),201)}
 if(method==='POST'&&route==='/obligations'){const data=await body(request);return json(await insert(env,'obligations',user,{title:text(data,'title',2,200),amount:number(data,'amount'),due_date:date(data,'due_date'),status:'Pendente'}),201)}
 if(method==='POST'&&route==='/messages'){const data=await body(request);return json(await insert(env,'messages',user,{body:text(data,'body',2,4000),role:'client'}),201)}
 if(method==='POST'&&route==='/documents'){if(!env.BUCKET)throw new HttpError(503,'Armazenamento temporariamente indisponível.');const bytes=await limitedBytes(request,MAX_FILE+100000);let data;try{data=await new Request(request.url,{method:'POST',headers:request.headers,body:bytes}).formData()}catch{throw new HttpError(400,'Arquivo inválido.')}const file=data.get('file');if(!file||typeof file==='string'||!file.size||file.size>MAX_FILE)throw new HttpError(400,'Envie um arquivo de até 10 MB.');const content=new Uint8Array(await file.arrayBuffer());const signature=String.fromCharCode(...content.slice(0,12));const allowed=(file.type==='application/pdf'&&signature.startsWith('%PDF-'))||(file.type==='image/png'&&content[0]===137&&signature.slice(1,4)==='PNG')||(file.type==='image/jpeg'&&content[0]===255&&content[1]===216&&content[2]===255)||(file.type==='image/webp'&&signature.startsWith('RIFF')&&signature.slice(8,12)==='WEBP');if(!allowed)throw new HttpError(400,'Formato não permitido. Use PDF, JPG, PNG ou WebP válidos.');const quota=await query(env,'SELECT COALESCE(SUM(size),0) AS bytes, COUNT(*) AS total FROM documents WHERE user_id = ?',user.id).first();if(quota.bytes+file.size>100*1024*1024||quota.total>=100)throw new HttpError(413,'O limite desta conta é de 100 arquivos ou 100 MB.');const id=crypto.randomUUID(),key=user.id+'/'+id,name=file.name.replace(/[\x00-\x1f\/\\]/g,'_').slice(0,180);await env.BUCKET.put(key,content,{httpMetadata:{contentType:file.type}});try{await query(env,'INSERT INTO documents (id,user_id,object_key,name,mime,size,created_at) VALUES (?,?,?,?,?,?,?)',id,user.id,key,name,file.type,file.size,new Date().toISOString()).run()}catch(err){await env.BUCKET.delete(key);throw err}return json({id,name,size:file.size},201)}
 if(method==='GET'&&/^\/documents\/[a-f0-9-]+$/.test(route)){const id=route.split('/')[2];const doc=await query(env,'SELECT * FROM documents WHERE id = ? AND user_id = ?',id,user.id).first();if(!doc)throw new HttpError(404,'Documento não encontrado.');if(!env.BUCKET)throw new HttpError(503,'Armazenamento indisponível.');const object=await env.BUCKET.get(doc.object_key);if(!object)throw new HttpError(404,'Documento não encontrado.');return new Response(object.body,{headers:{'Content-Type':doc.mime,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(doc.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}
 throw new HttpError(404,'Recurso não encontrado.');
}
function protect(response){const copy=new Response(response.body,response);copy.headers.set('X-Content-Type-Options','nosniff');copy.headers.set('Referrer-Policy','strict-origin-when-cross-origin');copy.headers.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');copy.headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://images.pexels.com data:; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com");return copy}
export default {async fetch(request,env,ctx){const url=new URL(request.url),user=identity(request);try{if(url.pathname.startsWith('/api/'))return protect(await handleApi(request,env,user,url));if(['/area-cliente','/cadastro'].some(p=>url.pathname===p||url.pathname.startsWith(p+'/'))&&!user)return Response.redirect(new URL('/signin-with-chatgpt?return_to='+encodeURIComponent(url.pathname+url.search),url),302);if(url.pathname==='/login'&&user)return Response.redirect(new URL('/area-cliente',url),302);if(!['GET','HEAD'].includes(request.method))return json({error:'Método não permitido.'},405);if(!env.ASSETS)throw new HttpError(503,'Site temporariamente indisponível.');return protect(await env.ASSETS.fetch(request))}catch(error){if(!(error instanceof HttpError))console.error('Request failed',url.pathname,error?.message);return protect(json({error:error instanceof HttpError?error.message:'Não foi possível concluir. Seus dados permanecem no formulário; tente novamente.'},error.status||503))}}};
